### PR TITLE
Fix event arguments

### PR DESCRIPTION
**Pull request by harry-cpp**

### CODE REVIEW

**Comment by mikkeljohnsen** [comment]
Are you absolutely sure this works. I am already using load-finished signal without problems ?

http://webkitgtk.org/reference/webkitgtk/stable/webkitgtk-webkitwebview.html#WebKitWebView-load-finished

Also state that the WebView should be there.

**Comment by harry-cpp** [comment]
Yea, without this I got argumentoutofrange exception, load-finished only had 1 argument associated and title-changed had 2.

**Comment by harry-cpp** [comment]
@mikkeljohnsen Turns out a bunch of other events suffer from the same problem (tested ~10 events, and automatically did it for the rest), I'm guessing that the `webview` argument is getting moved to `object sender`?

**Comment by mikkeljohnsen** [comment]
Ok, I will test tomorrow and merge if it works for me.

**Pull request merged**
